// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "path";
import { defineConfig } from "prisma/config";

config({ path: resolve(process.cwd(), ".env.local") });
config({ path: resolve(process.cwd(), ".env") });

/** Same rules as lib/db.ts: local + Vercel need public URL when DATABASE_URL is *.internal */
function resolveDatabaseUrl(): string {
  const privateUrl = process.env.DATABASE_URL?.trim() ?? "";
  const publicUrl = process.env.DATABASE_PUBLIC_URL?.trim() ?? "";
  const onRailwayRuntime = Boolean(process.env.RAILWAY_ENVIRONMENT);
  const looksLikeInternalOnly =
    privateUrl.includes("railway.internal") || /\.internal(?::|\/)?/i.test(privateUrl);

  if (process.env.VERCEL && publicUrl) return publicUrl;
  if (looksLikeInternalOnly && publicUrl && !onRailwayRuntime) return publicUrl;
  if (privateUrl) return privateUrl;
  return publicUrl;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: resolveDatabaseUrl(),
  },
});
